version: '3.8'
services:
  usersservice:
    build: .
    container_name: usersservice-container
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      # Use the database service name as host
      - ConnectionStrings__DefaultConnection=Host=dpg-d3al1st6ubrc739tdk20-a.oregon-postgres.render.com;Database=perla_metro_users;Username=perla_metro_users_user;Password=75jPMl3rdEB9lT7vqOXbOW1lbEcojMwE
      - Jwt__Key=your-super-secret-key-that-is-at-least-256-bits-long
      - Jwt__Issuer=http://localhost:5051
      - Jwt__Audience=http://localhost:5045
    depends_on:
      - database
    networks:
      - app-network

  database:
    image: postgres:15
    container_name: postgres-container
    environment:
      - POSTGRES_DB=perla_metro_users
      - POSTGRES_USER=perla_metro_users_user
      - POSTGRES_PASSWORD=75jPMl3rdEB9lT7vqOXbOW1lbEcojMwE
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge